/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupem;

import static groupem.GroupEm.eventss;
import static groupem.GroupEm.hp;
import static groupem.GroupEm.updateUserEvents;
import static groupem.GroupEm.userUsername;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author walter
 */
public class CreateEventPage extends javax.swing.JFrame {

    /**
     * Creates new form CreateEventPage
     */
    public CreateEventPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        dateText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        cancelCreate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(682, 318));
        setPreferredSize(new java.awt.Dimension(599, 451));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        jLabel1.setText("Event Name: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 150, 80, 17);

        jLabel2.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        jLabel2.setText("Date:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 190, 32, 17);

        jLabel3.setFont(new java.awt.Font("Effra", 0, 24)); // NOI18N
        jLabel3.setText("Description:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 220, 150, 30);

        nameText.setBorder(null);
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        getContentPane().add(nameText);
        nameText.setBounds(150, 151, 192, 16);

        dateText.setBorder(null);
        getContentPane().add(dateText);
        dateText.setBounds(150, 190, 190, 16);

        descText.setColumns(20);
        descText.setRows(5);
        descText.setBorder(null);
        jScrollPane1.setViewportView(descText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(101, 249, 244, 84);

        jLabel4.setFont(new java.awt.Font("Effra", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(112, 137, 182));
        jLabel4.setText("Create New Event");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(76, 89, 293, 44);

        createButton.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        createButton.setText("create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createButton);
        createButton.setBounds(339, 345, 81, 29);

        cancelCreate.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        cancelCreate.setText("cancel");
        cancelCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCreateActionPerformed(evt);
            }
        });
        getContentPane().add(cancelCreate);
        cancelCreate.setBounds(25, 345, 80, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CreateEvent.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 450, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        System.out.println(eventss.toString());
        Event e = new Event(nameText.getText(), userUsername, descText.getText(), dateText.getText());
        e.addInvitee(userUsername);
        eventss.add(e);
        updateUserEvents(userUsername);
        dispose();
        System.out.println(eventss.toString());
        HomePage hp9 = new HomePage();
        hp9.setResizable(false);
        hp9.setSize(451,487);
        hp9.setLocationRelativeTo(this);
        hp9.setVisible(true);
    }//GEN-LAST:event_createButtonActionPerformed

    private void cancelCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCreateActionPerformed
        //setVisible(false);
        
        HomePage hp1 = new HomePage();
        hp1.setLocationRelativeTo(this);
        hp1.setResizable(false);
        hp1.setSize(451,487);
        hp1.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_cancelCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateEventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateEventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateEventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateEventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEventPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelCreate;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField dateText;
    private javax.swing.JTextArea descText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameText;
    // End of variables declaration//GEN-END:variables
}
