/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupem;

import static groupem.GroupEm.hp;
import static groupem.GroupEm.userUsername;

/**
 *
 * @author walter
 */
public class EventPage extends javax.swing.JFrame{
    
    public static Event event;
    /**
     * Creates new form EventPage
     */
    public EventPage(Event e) {
        event = e;
        initComponents();
        refresh();
    }

    private EventPage() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventTitle = new javax.swing.JLabel();
        eventDescriptionLabel = new javax.swing.JLabel();
        eventDescriptionText = new javax.swing.JLabel();
        eventDateLabel = new javax.swing.JLabel();
        eventDateText = new javax.swing.JLabel();
        eventDateLabel1 = new javax.swing.JLabel();
        eventCreatorText = new javax.swing.JLabel();
        eventDateLabel2 = new javax.swing.JLabel();
        eventDateText2 = new javax.swing.JLabel();
        eventInviteesText = new javax.swing.JLabel();
        eventDateLabel3 = new javax.swing.JLabel();
        back_from_event = new javax.swing.JButton();
        add_comment = new javax.swing.JButton();
        add_invite = new javax.swing.JButton();
        inviteText = new javax.swing.JTextField();
        commentText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventCommentsText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        eventTitle.setFont(new java.awt.Font("Effra", 0, 24)); // NOI18N
        eventTitle.setForeground(new java.awt.Color(112, 137, 182));
        eventTitle.setText("jLabel1");
        getContentPane().add(eventTitle);
        eventTitle.setBounds(30, 40, 300, 40);

        eventDescriptionLabel.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        eventDescriptionLabel.setText("Description: ");
        getContentPane().add(eventDescriptionLabel);
        eventDescriptionLabel.setBounds(30, 80, 81, 16);

        eventDescriptionText.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        eventDescriptionText.setText("jLabel1");
        getContentPane().add(eventDescriptionText);
        eventDescriptionText.setBounds(130, 80, 310, 17);

        eventDateLabel.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        eventDateLabel.setText("Date:");
        getContentPane().add(eventDateLabel);
        eventDateLabel.setBounds(30, 100, 33, 16);

        eventDateText.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        eventDateText.setText("jLabel1");
        getContentPane().add(eventDateText);
        eventDateText.setBounds(130, 100, 300, 17);

        eventDateLabel1.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        eventDateLabel1.setText("Creator:");
        getContentPane().add(eventDateLabel1);
        eventDateLabel1.setBounds(29, 120, 95, 16);

        eventCreatorText.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        eventCreatorText.setText("jLabel1");
        getContentPane().add(eventCreatorText);
        eventCreatorText.setBounds(130, 120, 300, 17);

        eventDateLabel2.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        eventDateLabel2.setText("Invitees:");
        getContentPane().add(eventDateLabel2);
        eventDateLabel2.setBounds(30, 140, 95, 16);
        getContentPane().add(eventDateText2);
        eventDateText2.setBounds(216, 143, 0, 0);

        eventInviteesText.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        eventInviteesText.setText("jLabel1");
        getContentPane().add(eventInviteesText);
        eventInviteesText.setBounds(130, 140, 305, 19);

        eventDateLabel3.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        eventDateLabel3.setText("Comments:");
        eventDateLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(eventDateLabel3);
        eventDateLabel3.setBounds(30, 160, 95, 16);

        back_from_event.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        back_from_event.setText("back");
        back_from_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_from_eventActionPerformed(evt);
            }
        });
        getContentPane().add(back_from_event);
        back_from_event.setBounds(6, 6, 75, 29);

        add_comment.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        add_comment.setText("comment");
        add_comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_commentActionPerformed(evt);
            }
        });
        getContentPane().add(add_comment);
        add_comment.setBounds(10, 400, 100, 20);

        add_invite.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        add_invite.setText("invite");
        add_invite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_inviteActionPerformed(evt);
            }
        });
        getContentPane().add(add_invite);
        add_invite.setBounds(40, 430, 70, 20);

        inviteText.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        inviteText.setBorder(null);
        inviteText.setPreferredSize(new java.awt.Dimension(200, 25));
        inviteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteTextActionPerformed(evt);
            }
        });
        getContentPane().add(inviteText);
        inviteText.setBounds(120, 430, 320, 20);

        commentText.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        commentText.setBorder(null);
        commentText.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(commentText);
        commentText.setBounds(120, 400, 320, 20);

        eventCommentsText.setEditable(false);
        eventCommentsText.setBackground(new java.awt.Color(252, 252, 252));
        eventCommentsText.setColumns(20);
        eventCommentsText.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        eventCommentsText.setRows(5);
        eventCommentsText.setAutoscrolls(false);
        eventCommentsText.setBorder(null);
        jScrollPane1.setViewportView(eventCommentsText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(29, 186, 405, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EventPage.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inviteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inviteTextActionPerformed

    private void add_commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_commentActionPerformed
        if(!commentText.getText().equals("")){
            event.addComment(commentText.getText(), userUsername);
            eventCommentsText.setText(event.commentToString());
            System.out.println(event.commentToString());
            commentText.setText("");
            commentText.setSize(320, 20);
        }
    }//GEN-LAST:event_add_commentActionPerformed

    private void add_inviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_inviteActionPerformed
        if(!inviteText.getText().equals("")){
            event.addInvitee(inviteText.getText());
            eventInviteesText.setText(event.inviteeToString());
            System.out.println(event.inviteeToString());
            inviteText.setText("");
            inviteText.setSize(320, 20);
        }
    }//GEN-LAST:event_add_inviteActionPerformed

    private void back_from_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_from_eventActionPerformed
        
        HomePage hp5 = new HomePage();
        hp5.setResizable(false);
        hp5.setSize(451,487);
        hp5.setVisible(true);
        hp5.setLocationRelativeTo(this);
        setVisible(false);
    }//GEN-LAST:event_back_from_eventActionPerformed

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        System.out.println("Event Page ---  X: " + getX() + "   Y: " + getY() + "    height: " + this.getSize().height +  "  width: " + this.getSize().width);
    }//GEN-LAST:event_formComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventPage().setVisible(true);
            }
        });
        
        
    }
    
    private void refresh() {
        eventDescriptionText.setText(event.description);
        eventCommentsText.setText(event.commentToString());
        eventCreatorText.setText(event.creator);
        eventInviteesText.setText(event.inviteeToString());
        eventDateText.setText(event.date);
        eventTitle.setText(event.name);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_comment;
    private javax.swing.JButton add_invite;
    private javax.swing.JButton back_from_event;
    private javax.swing.JTextField commentText;
    private javax.swing.JTextArea eventCommentsText;
    private javax.swing.JLabel eventCreatorText;
    private javax.swing.JLabel eventDateLabel;
    private javax.swing.JLabel eventDateLabel1;
    private javax.swing.JLabel eventDateLabel2;
    private javax.swing.JLabel eventDateLabel3;
    private javax.swing.JLabel eventDateText;
    private javax.swing.JLabel eventDateText2;
    private javax.swing.JLabel eventDescriptionLabel;
    private javax.swing.JLabel eventDescriptionText;
    private javax.swing.JLabel eventInviteesText;
    private javax.swing.JLabel eventTitle;
    private javax.swing.JTextField inviteText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
