/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupem;

import static groupem.GroupEm.userUsername;

/**
 *
 * @author walter
 */
public class EventPage extends javax.swing.JFrame{
    
    public static Event event;
    /**
     * Creates new form EventPage
     */
    public EventPage(Event e) {
        event = e;
        initComponents();
        refresh();
    }

    private EventPage() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventTitle = new javax.swing.JLabel();
        eventDescriptionLabel = new javax.swing.JLabel();
        eventDescriptionText = new javax.swing.JLabel();
        eventDateLabel = new javax.swing.JLabel();
        eventDateText = new javax.swing.JLabel();
        eventDateLabel1 = new javax.swing.JLabel();
        eventCreatorText = new javax.swing.JLabel();
        eventDateLabel2 = new javax.swing.JLabel();
        eventDateText2 = new javax.swing.JLabel();
        eventInviteesText = new javax.swing.JLabel();
        eventDateLabel3 = new javax.swing.JLabel();
        eventCommentsText = new javax.swing.JLabel();
        back_from_event = new javax.swing.JButton();
        add_comment = new javax.swing.JButton();
        add_invite = new javax.swing.JButton();
        inviteText = new javax.swing.JTextField();
        commentText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eventTitle.setText("jLabel1");

        eventDescriptionLabel.setText("Description: ");

        eventDescriptionText.setText("jLabel1");

        eventDateLabel.setText("Date:");

        eventDateText.setText("jLabel1");

        eventDateLabel1.setText("Creator:");

        eventCreatorText.setText("jLabel1");

        eventDateLabel2.setText("Invitees:");

        eventInviteesText.setText("jLabel1");

        eventDateLabel3.setText("Comments:");
        eventDateLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        eventCommentsText.setText("jLabel1");

        back_from_event.setText("back");

        add_comment.setText("comment");
        add_comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_commentActionPerformed(evt);
            }
        });

        add_invite.setText("invite");
        add_invite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_inviteActionPerformed(evt);
            }
        });

        inviteText.setText("enter_invite");
        inviteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteTextActionPerformed(evt);
            }
        });

        commentText.setText("enter_comment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(add_comment)
                        .addGap(18, 18, 18)
                        .addComponent(commentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_from_event)
                        .addGap(53, 53, 53)
                        .addComponent(eventTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eventDateLabel)
                                .addGap(67, 67, 67)
                                .addComponent(eventDateText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eventDescriptionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(eventDescriptionText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eventDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(eventDateText2))
                                    .addComponent(eventCreatorText)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eventDateLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inviteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventInviteesText)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_invite)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(eventDateLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eventCommentsText, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(eventTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_from_event)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDescriptionLabel)
                    .addComponent(eventDescriptionText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDateLabel)
                    .addComponent(eventDateText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDateLabel1)
                    .addComponent(eventCreatorText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventDateText2)
                    .addComponent(add_invite)
                    .addComponent(inviteText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDateLabel2)
                    .addComponent(eventInviteesText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_comment)
                    .addComponent(commentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDateLabel3)
                    .addComponent(eventCommentsText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inviteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inviteTextActionPerformed

    private void add_commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_commentActionPerformed
        if(!commentText.getText().equals("")){
            event.addComment(commentText.getText(), userUsername);
            eventCommentsText.setText(event.commentToString());
            System.out.println(event.commentToString());
            commentText.setText("");
            commentText.setSize(WIDTH, HEIGHT);
        }
    }//GEN-LAST:event_add_commentActionPerformed

    private void add_inviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_inviteActionPerformed
        if(!inviteText.getText().equals("")){
            event.addInvitee(inviteText.getText());
            eventInviteesText.setText(event.inviteeToString());
            System.out.println(event.inviteeToString());
            inviteText.setText("");
        }
    }//GEN-LAST:event_add_inviteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventPage().setVisible(true);
            }
        });
        
        
    }
    
    private void refresh() {
        eventDescriptionText.setText(event.description);
        eventCommentsText.setText(event.commentToString());
        eventCreatorText.setText(event.creator);
        eventInviteesText.setText(event.inviteeToString());
        eventDateText.setText(event.date);
        eventTitle.setText(event.name);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_comment;
    private javax.swing.JButton add_invite;
    private javax.swing.JButton back_from_event;
    private javax.swing.JTextField commentText;
    private javax.swing.JLabel eventCommentsText;
    private javax.swing.JLabel eventCreatorText;
    private javax.swing.JLabel eventDateLabel;
    private javax.swing.JLabel eventDateLabel1;
    private javax.swing.JLabel eventDateLabel2;
    private javax.swing.JLabel eventDateLabel3;
    private javax.swing.JLabel eventDateText;
    private javax.swing.JLabel eventDateText2;
    private javax.swing.JLabel eventDescriptionLabel;
    private javax.swing.JLabel eventDescriptionText;
    private javax.swing.JLabel eventInviteesText;
    private javax.swing.JLabel eventTitle;
    private javax.swing.JTextField inviteText;
    // End of variables declaration//GEN-END:variables
}
