/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupem;

import static groupem.GroupEm.passwords;
import static groupem.GroupEm.userPass;
import static groupem.GroupEm.userUsername;
import static groupem.GroupEm.usernames;
import static groupem.GroupEm.loggedIn;
import static groupem.GroupEm.getUserIndex;
import static groupem.GroupEm.updateUserEvents;
import static groupem.GroupEm.userEventNames;
import static java.awt.Color.green;
import static java.awt.Color.red;
import java.util.Arrays;

/**
 * Login Page for GroupEm
 * CSC 3380 Project
 * @author Walter Scott, Ian Andrepont, Leigh Wright, Scott Walker
 * @since 11/27/18
 * @see GroupEm, Event, HomePage, EventPage, CreatePage
 */


public class Login extends javax.swing.JDialog {

//    ArrayList<String> usernames = new ArrayList<>();
//    ArrayList<String> passwords = new ArrayList<>();
//    String userPass;
//    String userUsername;
    java.awt.Frame p;
    
    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        p = parent;
        //this.passwords = new ArrayList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        signinButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        invalid_text = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(765, 360));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 191, 255));
        jLabel1.setFont(new java.awt.Font("Effra", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 137, 182));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GroupEm");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 130, 310, 43);

        usernameText.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        usernameText.setBorder(null);
        usernameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFocusLost(evt);
            }
        });
        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });
        getContentPane().add(usernameText);
        usernameText.setBounds(130, 190, 150, 17);

        jLabel2.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        jLabel2.setText("username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 190, 80, 16);

        jLabel3.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        jLabel3.setText("password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 220, 80, 16);

        signinButton.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        signinButton.setText("sign in");
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signinButton);
        signinButton.setBounds(170, 260, 87, 29);

        signupButton.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        signupButton.setText("sign up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signupButton);
        signupButton.setBounds(60, 260, 91, 29);

        invalid_text.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        invalid_text.setForeground(new java.awt.Color(225, 0, 0));
        invalid_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invalid_text.setText("             ");
        getContentPane().add(invalid_text);
        invalid_text.setBounds(30, 240, 260, 20);

        passwordText.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        passwordText.setBorder(null);
        getContentPane().add(passwordText);
        passwordText.setBounds(130, 220, 150, 17);

        close.setFont(new java.awt.Font("Effra", 0, 13)); // NOI18N
        close.setText("close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(120, 290, 77, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GroupEm Login.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 330, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernameTextActionPerformed

    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        // TODO add your handling code here:
        userUsername = usernameText.getText();
        userPass = passwordText.getText();
        //userPass = passwordText.getPassword();
        //userPass = passwordText.getp
        
        
        boolean isUser = usernames.contains(userUsername);
        if (userUsername.equalsIgnoreCase("") && userPass.equalsIgnoreCase("")){
            invalid_text.setForeground(red.darker());
            invalid_text.setText("Please Enter Your Username and Password");
        }
            
        else if (userUsername.equalsIgnoreCase("")){
            invalid_text.setForeground(red.darker());
            invalid_text.setText("Please Enter Your Username");
            
        }
            
        else if (userPass.equalsIgnoreCase("")){
            invalid_text.setForeground(red.darker());
            invalid_text.setText("Please Enter Your Password");
        }
            
        else if(!isUser){
            invalid_text.setForeground(red.darker());
            invalid_text.setText("Incorrect Username or Password");
        }
            
      
        int userIndex = getUserIndex(userUsername);
        System.out.println("INDEX: "+ userIndex);
        boolean correctPassword = passwords.get(userIndex).equals(userPass);
        if(userPass.contentEquals("")){
            invalid_text.setForeground(red.darker());
            invalid_text.setText("Hello, " + userUsername + ". Please enter your password");
            return;
        }
        if(!correctPassword) {
            invalid_text.setForeground(red.darker());
            invalid_text.setText("Incorrect Username or Password");
            return;
        }
        
        System.out.println("Username and Password Verified");
        loggedIn = true;
        System.out.println("userEventNames before: " + Arrays.toString(userEventNames));
        //System.out.println("userEvents before: " + userEvents.toString());
        updateUserEvents(userUsername);
        System.out.println("userEventNames after: " + Arrays.toString(userEventNames));
        //System.out.println("userEvent after: " + userEvents.toString());
        
        HomePage hp4 = new HomePage();
        hp4.setResizable(false);
        hp4.setSize(451,487);
        hp4.setVisible(loggedIn);
        hp4.setLocationRelativeTo(this);
        setVisible(false);
        //hp.setVisible(loggedIn);
        
        
        
    }//GEN-LAST:event_signinButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        //System.out.println(pass_text_entered);
        
        userUsername = usernameText.getText();
        userPass = passwordText.getText();
        
        boolean isUser = usernames.contains(userUsername);
        if (userUsername.equalsIgnoreCase("") && userPass.equalsIgnoreCase("")){
            invalid_text.setForeground(red.darker());
            invalid_text.setText("You must enter a username and password");
        }
        else if(userUsername.equalsIgnoreCase("")){
            invalid_text.setForeground(red.darker());
            invalid_text.setText("You must enter a username");
        }
        else if(userPass.equalsIgnoreCase("")){
            invalid_text.setForeground(red.darker());
            invalid_text.setText("You must enter a password");
        }
        else if(isUser) {
            invalid_text.setForeground(red.darker());
            invalid_text.setText("Username already exists");
        } else {
            usernames.add(userUsername);
            passwords.add(userPass);
            invalid_text.setForeground(green.darker());
            invalid_text.setText("You may now sign in.");
            
        }
        System.out.println("usernames: " + usernames.toString());
        System.out.println("passwords: " + passwords.toString());

        
    }//GEN-LAST:event_signupButtonActionPerformed

    private void usernameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernameTextFocusLost

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        System.out.println("LOGIN ---  X: " + getX() + "   Y: " + getY() + "    height: " + this.getSize().height +  "  width: " + this.getSize().width);
    }//GEN-LAST:event_formComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel invalid_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton signinButton;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
